import streamlit as st
st.title("Certificates: ")
st.divider()
st.subheader("Python IDLE")
st.write('''From:  IKON COMPUTER TRAINING CENTER''')
st.write("  GRADE-‘E’ ")
st.markdown("[Python-IDLE](https://www.linkedin.com/posts/masud-mallik-a27538334_python-pythonidle-programming-activity-7323387597634891776-T4Ww?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAFQVqr8BvHwLpVRLK_qrfIBai4MsKzkBOx4)")
st.subheader("C")
st.write('''From:  IKON COMPUTER TRAINING CENTER''')
st.write("  GRADE-‘AA’ ")
st.markdown("[C programing lang](https://www.linkedin.com/posts/masud-mallik-a27538334_cprogramming-coding-softwaredevelopment-activity-7323383546205585408-8DJl?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAFQVqr8BvHwLpVRLK_qrfIBai4MsKzkBOx4)")
st.subheader("DSA")
st.write('''From:  IKON COMPUTER TRAINING CENTER''')
st.write("  GRADE-‘AA’ ")
st.markdown("[DSA in C](https://www.linkedin.com/posts/masud-mallik-a27538334_datastructures-clanguage-programming-activity-7323385024228061185-sRpx?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAFQVqr8BvHwLpVRLK_qrfIBai4MsKzkBOx4)")