import streamlit as st
st.title("Projects")
st.divider()
st.subheader("Shop Management System ")
st.html(''' <h4>Developed a Shop Management System using Python, integrating Tkinter for GUI, MySQL for database management, and Matplotlib for data visualization of sales and stock trends.Designed interactive Tkinter-based user interfaces for product entry, billing, customer management, and stock tracking.</h4>''')
st.write("MAY 2025-JUN 2025")
st.write("Skills: MySQL · Python (Programming Language) · Graphical User Interface (GUI) · Data Visualization · Matplotlib")
st.markdown("[project shop menagement system](https://github.com/MasudMallik/shop_management)")

st.subheader("Mini Projects: ")
st.divider()
st.subheader("Background-remover-using-python")
st.write("MAY 2025-MAY 2025")
st.html(''' Developed a user-friendly image background removal application using Python, Tkinter, and the rembg library. The tool enables users to easily upload images, process them to remove backgrounds, and save the results in a desired format..</h4>''')
st.write("Skills: Python (Programming Language) · Graphical User Interface (GUI)")
st.markdown("[Background remover](https://github.com/MasudMallik/background-remover-using-python)")
st.subheader("QR Code Generator – Python GUI Application")
st.write("MAY 2025-MAY 2025")
st.html(''' Developed a user-friendly desktop application using Python and Tkinter to generate QR codes from custom URLs. The app features dynamic color customization, instant preview, and optional PNG file saving with user-defined names. It ensures smooth functionality with robust input validation and error handling. Demonstrates expertise in GUI development, user input handling, third-party library integration, and clean application design.</h4>''')
st.write("Skills: Python (Programming Language) · Graphical User Interface (GUI)")
st.markdown("[qrcode generator](https://github.com/MasudMallik/qrcode_generator)")

st.subheader("Java Tic-Tac-Toe game")
st.write("JULY 2025-JULY 2025")
st.html('''<h4>A classic Tic-Tac-Toe game, built entirely using Java Swing and JFrame in Apache NetBeans</h4>''')
st.write("Skills:JAVA")
st.markdown("[Tic-Tac-Toe](https://www.linkedin.com/posts/masud-mallik-a27538334_java-javaswing-netbeans-activity-7350498485269368833-h6eR?utm_source=social_share_send&utm_medium=android_app&rcm=ACoAAFQVqr8BvHwLpVRLK_qrfIBai4MsKzkBOx4&utm_campaign=copy_link)")