import streamlit as st
st.title("Skills")
st.subheader("Programming Languages:")
st.divider()
st.write("Python,C, R , Prolog,JAVA,")
st.subheader("Python:")
st.write("Tkinter (GUI), matplotlib (DATA VISUALIZATION), pandas,streamlit(frontend)")
st.divider() 
st.subheader("Data Structure And Algorithms (DSA):")
st.write("Array, Linked List, Stack, Queues, Trees, Graphs Sorting and Searching (binary and Linear)")
st.divider()
st.subheader("Data Base:")
st.write("MySQL")
st.divider()
st.subheader("Tools and Platforms:")
st.write("Python IDLE, VS Code, SWI-Prolog, Spyder, Google Colab, DEV C++")
